services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/lsouquie/volumes:/var/www/html
    depends_on:
      - wordpress

  
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - /home/lsouquie/volumes:/var/www/html
