FROM debian:11.11

RUN apt update && apt upgrade -y && apt install -y mariadb-server

COPY mariadb.conf /etc/mysql/mariadb.conf.d/.
COPY init.sql /etc/mysql/init.sql

RUN mkdir /run/mysql


CMD ["mysqld_safe"]