FROM debian:11.11

RUN apt update && apt install -y \
    php php-fpm \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN rm /etc/php/7.4/fpm/pool.d/*.conf

COPY wp.conf /etc/php/7.4/fpm/pool.d/.

RUN sed -i 's|listen = /run/php/php7.4-fpm.sock|listen = 9000|' /etc/php/7.4/fpm/pool.d/wp.conf

RUN mkdir -p /run/php

CMD ["php-fpm7.4", "-F"]

# CMD tail -f /dev/null