FROM debian:11.11

RUN apt update && apt install -y \
    php php-fpm \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN rm /etc/php/7.4/fpm/pool.d/*.conf

COPY wp.conf /etc/php/7.4/fpm/pool.d/.

COPY setup.sh /setup.sh

RUN chmod 644 /etc/php/7.4/fpm/pool.d/wp.conf

# RUN sed -i 'listen = 0.0.0.0:9000|' /etc/php/7.4/fpm/pool.d/wp.conf

RUN mkdir -p /run/php

CMD ["/setup.sh"]

# CMD tail -f /dev/null