FROM debian:11.11

RUN apt update && apt install -y \
    php php-fpm wget \
    mariadb-client php7.4-fpm \
    php7.4-gd php7.4-mbstring php7.4-zip \
    php7.4-intl php7.4-curl \
    php-mysqli \
    php7.4-mysql \
    php7.4-xml \
    php-imagick \
    curl \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN rm /etc/php/7.4/fpm/pool.d/*.conf

COPY wp.conf /etc/php/7.4/fpm/pool.d/.
COPY setup.sh /setup.sh

# RUN chmod +x /setup.sh

RUN chmod 644 /etc/php/7.4/fpm/pool.d/wp.conf

# RUN sed -i 'listen = 0.0.0.0:9000|' /etc/php/7.4/fpm/pool.d/wp.conf

RUN mkdir -p /run/php

CMD ["/setup.sh"]

# CMD tail -f /dev/null