FROM debian:11.11

# Installer Nginx et OpenSSL
RUN apt update && apt install -y \
    nginx \
    openssl \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Créer le répertoire pour les certificats SSL
RUN mkdir -p /etc/nginx/ssl

# Générer un certificat SSL auto-signé
RUN openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/server.key \
    -x509 -days 365 -out /etc/nginx/ssl/server.crt \
    -subj "/CN=localhost"

# Copier la configuration Nginx
COPY nginx.conf /etc/nginx/sites-available


# Exposer le port 443 pour HTTPS
EXPOSE 443

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
